name: Build ratelimiting
on:
  pull_request:
    branches:
      - master
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:bionic
    
    steps:          
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Build
        run: |
          go build .
      
      - name: Test
        run: |
          go test ./...
        
